### ISSUE TITLE
Only 3 lines of SQL visible until you resize the query window

### ISSUE THREAD

**Issue by chrismore** [mozilla/redash#788] opened 2019-01-25 21:48 UTC
### Issue Summary

A few months ago when viewing a redash query, my entire query window only display the top 3 lines of SQL while the rest is completely blank. I can only scroll within these 3 lines. It looks like a CSS or rendering issue.

### Steps to Reproduce

1. Open up any redash query
2. Edit the source
3. View the SQL

Expected results:

Seeing all of the SQL with scroll bars

Actual results:

Only 3 lines of SQL are visible and the rest of the query window is blank. You can scroll up/down, but only the top 3 lines are visible. If I resize the query window vertically (with the two horizontal lines below the save/execute buttons), the expected results happens, but only temporarily. If I refresh the page after resizing the query, the issue happens again. This started a few months ago and I have no clear path to resolution.

Screenshot of hidden query:

<img width="475" alt="screen shot 2019-01-25 at 12 48 37 pm" src="https://user-images.githubusercontent.com/751491/51774563-5eea5e80-20b8-11e9-8f59-c43a77aa3f75.png">

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: web
* Browser/OS: Firefox Release channel + Mac OSX
* How did you install Redash: Browser based, nothing to install. I tried to log out and back in with no hope.

**Comment by harterrt** [comment] 2019-01-25 22:59
I've been experiencing the same bug for the last week as well.

**Comment by fbertsch** [comment] 2019-01-28 17:11
Bump, there's at least 2 others in the fx-metrics channel who have experienced this.

**Comment by harterrt** [comment] 2019-01-28 18:25
@rafrombrc, can you confirm someone is looking at this?

**Comment by chrismore** [comment] 2019-01-30 15:18
I also want to note that this is a Firefox-only bug. I do not experience this within Chrome. It could be related to scroll anchoring: https://bugzilla.mozilla.org/show_bug.cgi?id=1519644

**Comment by fbertsch** [comment] 2019-01-30 17:25
@chrismore maybe disabling the scroll anchoring will help? Though I think that's nightly-only. If it's available in your config, set `layout.css.scroll-anchoring.enabled` to `false`. Let us know if that fixes things.

**Comment by fbertsch** [comment] 2019-01-30 17:52
@chrismore thanks for investigating, I couldn't get it to reproduce either.

**Comment by jezdez** [comment] 2019-02-06 11:45
@chrismore @fbertsch I wasn't able to reproduce this in 65, were you?

**Comment by jezdez** [comment] 2019-02-06 19:04
@emtwo @washort I was able to reproduce this a few days ago, but can't anymore. Have you seen this recently?

**Comment by emtwo** [comment] 2019-02-06 19:11
Likewise, I cannot reproduce this anymore.

**Comment by chrismore** [comment] 2019-02-06 21:01
In Firefox 65, I am unable to reproduce it anymore.

**Comment by jezdez** [comment] 2019-02-07 14:51
Turns out this has not been an issue in Firefox anymore but Chrome still has it. Good news is it was fixed upstream via https://github.com/getredash/redash/pull/3412.

@rafrombrc Just to make sure, is this something we should close now or leave open until we've pulled in the change in the next rebase?

**Comment by rafrombrc** [comment] 2019-02-20 17:43
Let's leave it open until we merge.

**Comment by rafrombrc** [comment] 2019-02-20 18:44
Closing since this has been resolved in firefox.

**Closed by rafrombrc** 2019-02-20 18:44 UTC
Labels: blocked
