### ISSUE TITLE
Refreshing Athena with Glue Catalog results in ISE OperationNotPageableError: Operation cannot be paginated: get_tables

### ISSUE THREAD

**Issue by jasonthomas** [mozilla/redash#352] opened 2018-03-27 19:53 UTC
In production when trying to refresh 'svcops_monitoring_reports' https://sentry.prod.mozaws.net/operations/data-stmo-prod/issues/1816044/

Looks like this is reported https://github.com/getredash/redash/issues/2400 and related to the version of botocore.

**Comment by jezdez** [comment] 2018-05-02 14:14
There are other things related to that runner, #371 and #370 (which may actually be a duplicate of this ticket). Easiest would be to merge upstream as soon as the fix for #371 in https://github.com/getredash/redash/pull/2503 merges.

**Closed** 2018-07-11 17:34 UTC
Labels: bug
