### ISSUE TITLE
A user that is granted permissions to a dashboard cannot grant permissions to others for the dashboard

### ISSUE THREAD

**Issue by emtwo** [mozilla/redash#346] opened 2018-02-28 16:15 UTC
STR:
1) Create a new dashboard
2) Give another person permission for the dashboard
3) The other person tries to give permission to a third person

Actual result: Silent failure. The user seems to be in the list but they don't have permissions to edit

Expected result: The permissions should either be added or an error is given that explains "permission denied"

**Comment by alison985** [comment] 2018-06-17 15:50
@emtwo How do you grant a user permissions to edit a dashboard? I am not seeing anything in the menus of a dashboard.

**Comment by jezdez** [comment] 2018-06-19 18:52
@alison985 This is how it looks like if I create a dashboard on stage:

![screen-shot-2018-06-19-20-45-14](https://user-images.githubusercontent.com/1610/41617887-f34cef5c-7401-11e8-9b3d-b1e48bcd33f0.png)

I wonder if this is a permission issue for you?

Looking at the code it uses [showPermissionsControl](https://github.com/getredash/redash/blob/5c1d2c88770c4729d21b3cacec32fe7ec0ef39e5/client/app/pages/dashboards/dashboard.html#L64) which ends up being set in the Redash settings system via the environment variable `REDASH_FEATURE_SHOW_PERMISSIONS_CONTROL` and [it defaults to `false`](https://github.com/getredash/redash/blob/5c1d2c88770c4729d21b3cacec32fe7ec0ef39e5/redash/settings/__init__.py#L211). Seems like this was enabled in stage/prod and you'll need to enable it locally, too.

**Comment by alison985** [comment] 2018-06-30 18:55
Yep, that configuration setting allowed me to see "Manage Permissions" in the menu. 

This is reproducible against upstream master. Submitted PR against upstream: https://github.com/getredash/redash/pull/2650

**Comment by jezdez** [comment] 2018-08-23 18:51
Merged upstream! ✨

**Closed by jezdez** 2018-08-23 18:51 UTC
Labels: in review, in review upstream

**Comment by vcarciu** [comment] 2018-09-07 15:32
Verified as fixed. An error explaining the permission denied is displayed: 
![permissions](https://user-images.githubusercontent.com/1583842/45228644-5f7e8600-b2cc-11e8-9f98-b1eaee4be41c.gif)
