### ISSUE TITLE
Long string that do not contain empty spaces are breaking the preview section layout in text widgets

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#326] opened 2018-01-30 10:59 UTC
### Steps to Reproduce:
1. Open this dashboard: https://pipeline-sql.stage.mozaws.net/dashboard/-test-test
2. Click on the option button - edit for the text widget that contains "11111111111111" string

### Expected results:
The preview section is displayed correctly

### Actual results:
Long strings are breaking the preview section. 

### Notes/Issues:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
Verified in FF58(Win7).  Issue can be reproduced in STMO-stage
![uichangespreviewtextwidget](https://user-images.githubusercontent.com/15685441/35562819-4ad666a8-05bd-11e8-866c-44838f749793.png)

**Comment by madalincm** [comment] 2018-02-26 13:40
Verified in FF58(Win7x64) in stmo-stage
Issue is still reporducing:
![326reopen](https://user-images.githubusercontent.com/15685441/36673380-4acfc858-1b0b-11e8-80fe-1d05c5784725.png)

**Comment by washort** [comment] 2018-03-07 22:24
this is occurring in production (m12.1) as well.

**Comment by jezdez** [comment] 2018-05-30 18:38
I *think* this was recently fixed upstream but can't find the commit right away.

**Comment by alison985** [comment] 2018-06-05 03:27
Just checked this on pipeline-sql since the upstream merge work should be there now and it is still reproducing.

**Comment by jezdez** [comment] 2018-06-05 17:52
Ah, dang, must have been a different commit I saw. Sorry for the noise.

**Comment by jezdez** [comment] 2018-06-18 16:06
I've closed https://github.com/mozilla/redash/pull/423 since the parent PR https://github.com/getredash/redash/pull/2580 has been merged. We'll keep this issue open though until we've merged upstream.

**Comment by alison985** [comment] 2018-08-08 15:31
The upstream changes should have been caught in the latest rebase from upstream, so I'm moving this to done so @madalincm  can check it.

**Closed** 2018-08-08 15:32 UTC
Labels: UI Changes, blocked, bug, merge upstream

**Comment by madalincm** [comment] 2018-08-08 15:42
Verified in FF61(Win7) in stmo-stage
Issue is no longer reproducing:
![longtextwidget](https://user-images.githubusercontent.com/15685441/43847984-9f18dbe8-9b3a-11e8-8f63-4bbb8ae0eb83.png)
