### ISSUE TITLE
Bar chart doesn't support one row result any more

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/redash#389] opened 2018-04-27 17:37 UTC
The recent release has broken this chart https://sql.telemetry.mozilla.org/queries/51784#138417

The query only returns one row with multiple columns, looks like bar chart does not support this kind of input any more. If that's by design, which alternative chart should I use instead?

**Comment by washort** [comment] 2018-05-02 21:36
This appears to be fixed in master.

**Closed by washort** 2018-05-02 21:36 UTC
Labels: ready

**Comment by madalincm** [comment] 2018-05-03 14:54
I have used this query(https://pipeline-sql.stage.mozaws.net/queries/373/source#458) in stage to test and for this example the issue is no longer reproducing. I'm not sure if this is enough to validate the fix. @washort  any thoughts on this?

**Comment by washort** [comment] 2018-05-03 15:02
I think it's good, the js console error message on prod points to code that @emtwo recently fixed.

**Comment by madalincm** [comment] 2018-05-09 13:48
Marking bug as verified fixed.
