### ISSUE TITLE
Make sso.mozilla.com users aware they should click "Remote User Login"

### ISSUE THREAD

**Issue by overholt** [mozilla/redash#802] opened 2019-02-05 14:50 UTC
### Make sso.mozilla.com users aware they should click "Remote User Login"

I'm using Firefox Nightly on Windows but I'm pretty sure this is OS/browser/architecture-agnostic

### Steps to Reproduce

1. Go to https://sql.telemetry.mozilla.org/ for the first time as a user with an mozilla.com LDAP account.
2. Be unsure how to log in :)

**Comment by jezdez** [comment] 2019-02-05 15:04
Thanks @overholt, that's a regression after a recent Redash update, I believe.

@jasonthomas Since the `REDASH_PASSWORD_LOGIN_ENABLED` env var seems to be set correctly in the ops configuration to "false" for prod the password login seems to be enabled in the organization settings in the admin section instead. Could make sure it's not enabled so the login format isn't shown?

https://pipeline-sql.stage.mozaws.net/login only shows the "remote login" button only, while http://sql.telemetry.mozilla.org/login shows the login form as well

**Comment by jasonthomas** [comment] 2019-02-05 16:34
I've modified `organizations.settings` and set `auth_password_login_enabled = false`.

**Comment by jezdez** [comment] 2019-02-05 16:39
@overholt So the verdict is that the existence of the `Remote User Login` button doesn't make any sense since we don't use any of the other login methods that Redash supports.

I've opened https://github.com/mozilla/redash-stmo/issues/17 to track the feature to simply redirect to our Auth0 based login flows (aka Mozilla SSO) instead of showing that button.

In the meantime @jasonthomas has hidden the confusing login form that was shown below the button.

**Comment by overholt** [comment] 2019-02-05 16:50
👍 thanks for the super-quick turnaround here!

**Comment by jezdez** [comment] 2019-08-07 17:30
Closing now that https://github.com/mozilla/redash-stmo/pull/26 got merged. This will be deployed this or next week.

**Closed by jezdez** 2019-08-07 17:30 UTC
