### ISSUE TITLE
A query is refreshed if another distinct identical query is executed

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#331] opened 2018-02-08 16:29 UTC
### Steps to Reproduce:
1.  Create a new query, save it and set the update schedule to a specific time.  (ex: https://pipeline-sql.stage.mozaws.net/queries/320/source)
-- wait at least a minute so that the last update value is something else the a few seconds ago
2.  Create a second query that has exactly the same code as the query from step 1. (i.e https://pipeline-sql.stage.mozaws.net/queries/321/source)
3.  Execute the second query.
4.  Go to the first query page and observe the last updated value

### Expected results:
The first query should be re-run only at the time set for the update schedule. The last update value is the moment the query was first run.

### Actual results:
The first query last update value is changing when the second query is run.

### Notes/Issues:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
Verified in FF58(Win7).  Issue can be reproduced in STMO-stage and STMO-prod
![queryrerun](https://user-images.githubusercontent.com/15685441/35984698-a665f726-0cfd-11e8-97d2-71182b5d2f1e.gif)

**Comment by rafrombrc** [comment] 2018-02-21 19:35
This is actually by design, the thinking is that redash has more recent results from the query, and so it's going to show those rather than showing what could be outdated results. Whether that's desired is up for discussion, but it's definitely a conscious choice made by redash to work this way.

**Comment by arikfr** [comment] 2018-02-22 07:01
It's indeed by design. The other reason was to avoid executing the same query more than once at the same time.

**Comment by jezdez** [comment] 2018-02-28 21:13
Closing as wontfix then.

**Closed by jezdez** 2018-02-28 21:13 UTC
Labels: bug
