### ISSUE TITLE
BigQuery Schemas are not showing

### ISSUE THREAD

**Issue by fbertsch** [mozilla/redash#916] opened 2019-02-28 15:45 UTC
At https://sql.telemetry.mozilla.org/queries/new, the schemas have stopped showing. I get an error that a schema refresh has failed.

**Comment by emtwo** [comment] 2019-02-28 19:29
Closing this as it's probably a dupe of https://github.com/mozilla/redash/issues/785 which will be available with the next merge. @fbertsch feel free to re-open if you think it's a different issue.

**Closed by emtwo** 2019-02-28 19:29 UTC

**Comment by fbertsch** [comment] 2019-02-28 19:47
I think you're right. I was mistaken because the schemas _did_ show for a little while, but that must have just been one of those happy accidents.
