### ISSUE TITLE
Recent Dashboards and Recent Queries slowly populated or not at all

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/redash#349] opened 2018-03-06 14:45 UTC
### Issue Summary

Firefox Nightly, latest versions, on Windows 8.1

For the last days, https://sql.telemetry.mozilla.org/ 's Recent Dashboards and Recent Queries populated slowly or this morning not at all.

### Steps to Reproduce

1. Load https://sql.telemetry.mozilla.org/
2. Wait if "Recent Dashboards" and "Recent Queries" get populated.

### Technical details:

* Redash Version: 3.0.0
* Browser/OS: Firefox Nightly 60.0a1, builds from this week
* How did you install Redash: N/A

**Comment by rafrombrc** [comment] 2018-05-30 18:54
We've upgraded the STMO database server, which should have had an improvement on this, hopefully it's not as bad as it was. We are still planning improvements to the search infrastructure (related #385) that should improve this even further.

**Comment by jezdez** [comment] 2018-07-18 16:22
This works for me at the moment, and I think we can assume the database upgrades helped.

Closing for now, but don't hesitate to bring it up again should you see it again.

**Closed by jezdez** 2018-07-18 16:22 UTC

**Comment by madalincm** [comment] 2018-07-31 12:59
Verified in FF61(Win7) in stmo-stage. I'm not able to reproduce this issue anymore. 
Marking this bug as verified fixed.
