### ISSUE TITLE
Group by text displayed in some charts is truncated

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#395] opened 2018-05-09 13:46 UTC
Steps to Reproduce:
1. Open https://pipeline-sql.stage.mozaws.net/queries/374#460
2. Hover over any of the bars in chart

Expected results:
All the information are displayed completely. For example when hovering over the blue bar the text: "App 2.0.1 - Android 22" is correctly displayed

Actual results:
When hovering over the blue bar the ""App 2.0.1 - Android 22"" text is truncated and only "App 2.0.1 - ..." is displaued

Notes/Issues:
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
Verified in FF59(Win7). Issue can be reproduced in STMO-stage and STMO-prod
Production query where this issue can be reproduced: https://sql.telemetry.mozilla.org/queries/52806#140500
Screencast for this issue:
![truncatedtext](https://user-images.githubusercontent.com/15685441/39817853-fafe9220-53a7-11e8-8591-75091b4a8919.png)

**Comment by alison985** [comment] 2018-06-03 02:36
I can reproduce this issue on redash v4.0.1+b838f28f if there are multiple series. On single series bar charts it doesn't even try to display the label. 

In order to see the HTML generated on hover you have to use Chrome and the "Break on > subtree modifications" feature. That points you to the d3.js file.

Plotly.js supports hover text:  https://plot.ly/javascript/bar-charts/#bar-chart-with-hover-text
I forked the codepen example and changed the plotly.js down to our version - 1.20.1 here: https://codepen.io/plotly/pen/c11f764ad9de0a40f3f4989517195cf0 (it's not saving the version change) It does allow untruncated labels to be passed into the `text` parameter.

Adding the `text` parameter and the name of the series to the plotlySeries in javascript (utils.js) does not fix the issue. `hoverinfo` and `hovertext` also do not fix the issue. 

Searching for '...', which is what is being appended to each label after truncation does not result in any leads.

**Comment by madalincm** [comment] 2018-06-19 12:54
Verified in FF60(Win7) in stmo-stage
The original issue appears to be fixed, the entire string is displayed:
![truncatedstring](https://user-images.githubusercontent.com/15685441/41598499-fd3caf94-73d8-11e8-8ff3-a0634a7cdc02.png)

But as can be observed in the above screenshot there is a problem with the text alignment. 
I will mark this issue as verified fixed an open an new one to track that.

**Comment by jezdez** [comment] 2018-06-21 19:02
Reopening since we decided to roll back #422 following a discussion with @emtwo on IRC about #437. 

The real culprit seems to be a missing feature in plotly (https://github.com/plotly/plotly.js/issues/460) and the best I was able to get to was: 

<img width="460" alt="em25uoxads8m0cq1wzhuvm234fc18ogo-medium" src="https://user-images.githubusercontent.com/1610/41739766-61ac93a4-7596-11e8-88ab-1f064c593660.png">

I'm really wondering if it's not enough to have the full label in the legend next to the graph?

**Comment by madalincm** [comment] 2018-06-22 09:14
@jezdez Having the value is what really counts so I agree with you that having the label correctly displayed next to the graph should be ok for now.

**Comment by alison985** [comment] 2018-06-22 12:09
@jezdez Are we closing as won't fix?

**Comment by jezdez** [comment] 2018-06-22 13:33
@alison985 Yeah, with @madalincm's reply above I think we can close this. At least until https://github.com/plotly/plotly.js/issues/460 is fixed.

**Closed by jezdez** 2018-06-22 13:33 UTC
Labels: bug, in review
