### ISSUE TITLE
Widget size selector is not displayed in the Add Widget window

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#324] opened 2018-01-29 13:16 UTC
### Steps to Reproduce:
1. Open a new dashboard page
2. Click on the options button and on the add widget link

### Expected results:
The option to add a regular or a double widget is displayed.

### Actual results:
Widget size selector is not displayed. The user can only insert a regular size widget.

### Notes/Issues:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
The user has the option to resize the widget after aiding it in the page from the Edit Layout menu but not when adding a new widget.
Verified in FF58(Win7).  Issue can be reproduced in STMO-stage

![uichangeswidgetsize](https://user-images.githubusercontent.com/15685441/35512054-05ad0bba-0507-11e8-8bb3-cae7c5435b4a.png)

**Comment by madalincm** [comment] 2018-02-26 13:43
Verified in FF58(Win7x64) in stmo-stage
Issue is still reproducing:
![324reopen](https://user-images.githubusercontent.com/15685441/36673555-c85d920a-1b0b-11e8-84f4-9069c2543b38.png)

**Comment by alison985** [comment] 2018-06-17 21:58
This reproduces on upstream code locally and on https://pipeline-sql.stage.mozaws.net/ I opened https://github.com/getredash/redash/issues/2595 as an issue upstream to see if this is intentional/desired in upstream before determining next steps.

**Comment by jezdez** [comment] 2018-06-18 17:30
Aha, as was explained in https://github.com/getredash/redash/issues/2595 this was removed from Redash since widgets can be resized individually since 4.x (merged in https://github.com/getredash/redash/pull/2062 via https://github.com/getredash/redash/commit/6a7d2291b4ca914e577a2e27729d28eacdae1263) and the dashboard engine was rewritten to accommodate it. Closing as wontfix.

**Closed by jezdez** 2018-06-18 17:30 UTC
Labels: UI Changes, bug, ready
