### ISSUE TITLE
Filtering queries by long tags crash the page

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#477] opened 2018-07-31 15:04 UTC
### Steps to Reproduce:
1. Create a long tag and add it to a query
2. Go to all queries page and from the right side menu click on the tag created in step 1

### Expected results:
The query with that tag is displayed

### Actual results:
The page crashes with a 400 error

### Notes/Issues:
Verified in FF61(Win7).  Issue can be reproduced in STMO-stage
![longtagerror](https://user-images.githubusercontent.com/15685441/43468209-187a34fa-94ec-11e8-8f7f-f2cd9df161b7.gif)

**Comment by washort** [comment] 2018-08-02 19:51
The error is "Request Line is too large (5931 > 4094)". Presumably there should be a limit on tag length.

**Comment by alison985** [comment] 2018-11-11 22:31
@madalincm  I can't reproduce this on my local anymore (from upstream master). Can you confirm it's handled please?

**Comment by jezdez** [comment] 2018-11-16 10:56
@madalincm Ping?

**Comment by madalincm** [comment] 2018-11-16 12:42
@alison985 Sorry for the delayed response.

The issue is still reproducing in STMO-rc.  When using a very long tag you will get a 414 error message Request URI Too Large.
![414](https://user-images.githubusercontent.com/15685441/48621902-be880780-e9ad-11e8-88e4-a8d27f4f3e32.png)

**Comment by alison985** [comment] 2018-11-18 21:21
I can't reproduce this on my local with upstream_master. I really think we just have to wait for the next merge from upstream back to the fork.

**Comment by jezdez** [comment] 2019-01-16 19:17
This should be fixed now. @madalincm Could you please verify?

**Closed by jezdez** 2019-01-16 19:17 UTC
Labels: bug, in review, merge upstream

**Comment by madalincm** [comment] 2019-03-28 07:58
Verified in FF66
The issue is still reproducingm the page crashes with a 414 error code but now we at least show a message:
Please view this screenshot: https://screenshots.firefox.com/DoVxaAS8pFLT9gOK/data-stmo-rc.stage.mozaws.net

Are we ok with this?

**Comment by washort** [comment] 2019-03-28 15:56
I don't think this should block us. I'll open an issue upstream as I can't find any work done to prevent this.

**Comment by madalincm** [comment] 2019-03-28 16:02
Yes, it should not block us, the issue is already in prod and the actual behaviour happening on RC is an impprovment as we are showing a message.
And having tags of that length is an small edge case.
