### ISSUE TITLE
Queries are not refreshed at the specific time set in the update schedule

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#332] opened 2018-02-08 16:35 UTC
### Steps to Reproduce:
1.  Create a new query and set the refresh schedule to a specific time (i.e: https://pipeline-sql.stage.mozaws.net/queries/315/source)
2. Wait for the specific time specified in step 1

### Expected results:
The query is refreshed at the specified time.

### Actual results:
The query is not refreshed at the specified time.

### Notes/Issues:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
Verified in FF58(Win7).  Issue can be reproduced in STMO-stage and STMO-prod
![updateshcedule](https://user-images.githubusercontent.com/15685441/35985146-9643a3f6-0cfe-11e8-9285-9fd292922eff.png)

**Comment by alison985** [comment] 2018-06-03 01:40
@madalincm Just a reminder to see if you can help me with reproducing this please.

**Comment by madalincm** [comment] 2018-06-19 15:37
Sorry for not seeing this issue earlier.
The second page is in here: https://pipeline-sql.stage.mozaws.net/users  I only used it to see when was the last time i was active on stmo so that i know how to set the refresh schedule on my query. You do not need that to reproduce the issue.
I'm still able to reproduce the issue using the same steps.
I set the refresh schedule everyday at a given hour for a query but the query is not refreshed when it should.
![queries_not_refreshing](https://user-images.githubusercontent.com/15685441/41607820-9c22cdee-73ef-11e8-919a-8243becb8d4d.png)

**Comment by alison985** [comment] 2018-06-22 15:38
I am not able to reproduce this. Here are the things I tried:

1. booted up getredash/redash and set a query to update every minute. Monitored http://0.0.0.0:5000/admin/queries/tasks#done for about 10 minutes. There were some 2 minute jumps between created at times, but I figured this could be because of some second issues or the one minute interval being too close together.

2. booted up Mozilla fork master and did the same query on an update every minute schedule. Again monitored, again saw the 2 minute issue, so I let it run every 5 minutes for. ~3 hours. Those times came out nice and always 5 minutes apart. see here: 
![screenshot 2018-06-22 10 34 05](https://user-images.githubusercontent.com/1840865/41785325-d5f1063e-7607-11e8-8498-ecf2a4ece688.png)

I switched tabs back to the query page and saw that it said it hadn't been updated in 3 hours even though I knew that to be false. I refreshed the page and it said updated as of a few seconds ago. I have now left the query tab open past the 5 minute refresh and it says updated 7 minutes ago even though it ran 2 minutes ago. see here: 
![screenshot 2018-06-22 10 36 10](https://user-images.githubusercontent.com/1840865/41785401-1efc7124-7608-11e8-9acf-67f1a43d5354.png)

I also notice that the last refresh time seems to change, it's counting forward from the last time the page was refreshed. 

I really don't think this is an issue or a bug. @jezdez can I close?

**Comment by madalincm** [comment] 2018-06-25 08:38
Thanks @alison985 for investigating on this issue. I tried to isolate my case where I reproduce the issue and I think I am on the right path. I will come with further comments

**Comment by madalincm** [comment] 2018-06-25 09:50
Later Edit:
1. There is an issue with the time formatting which made me set up my refresh schedules at an incorrect time ergo my queries were not refreshed when I expected. This issue is covered in #441 
2. After removing that factor some of my queries are still not refreshing.  After some investigation i have managed to better isolate the scenario.  The complete steps to reproduce are here: #442

**Comment by alison985** [comment] 2018-06-27 15:20
Thanks so much @madalincm. I'm closing this issue since #441 and #442 cover it.

**Closed by alison985** 2018-06-27 15:20 UTC
Labels: bug, in progress

**Comment by madalincm** [comment] 2018-06-29 12:20
Marking as a duplcate of #442
