### ISSUE TITLE
Server Code 500 on Public Dashboard URL

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/redash#166] opened 2017-07-26 17:43 UTC
### Issue Summary

Attempting to request the publicly shareable URL of a dashboard results in the server returning a 500 status code.
 
### Steps to Reproduce

1. Request a publicly shareable dashboard url ex: https://sql.telemetry.mozilla.org/public/dashboards/iADxJYpDKPqpF2T2k72mQNFxZYLDGe8XJ6Ot8ylK?org_slug=default
2. Receive 500

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

Should return 200 with a dashboard.

### Technical details:

* Redash Version:  Redash 2.0.0 
* Browser/OS: Firefox Nightly 56/OSX 10.12.4

**Comment by alison985** [comment] 2017-07-27 03:14
Hi @jaredkerim, could you please provide more information about how you find the "publicly sharable dashboard" option? The link to the original dashboard before getting a public URL would also be helpful. Thanks in advance.

**Comment by emtwo** [comment] 2017-07-27 17:24
In any dashboard in the top right corner there is a link (third from the left in the screenshot) to create a public link.
<img width="219" alt="screen shot 2017-07-27 at 1 18 24 pm" src="https://user-images.githubusercontent.com/784781/28683303-1c1b864a-72ce-11e7-8b1a-08c39c11c7b2.png">

I think this issue occurs with any dashboard

**Comment by alison985** [comment] 2017-07-28 11:40
Thanks @emtwo. @jaredkerim could you let me know the URL of the dashboard you started with to get that public URL please? I'm not able to reproduce it in production or my local with a random dashboard.

**Comment by jaredkerim** [comment] 2017-08-03 17:21
@alison985 

Here is a dashboard we generated recently:

https://sql.telemetry.mozilla.org/dashboard/activity-stream-experiment-experimenter-test-01

Here is its public shareable URL obtained using the method @emtwo explained:

https://sql.telemetry.mozilla.org/public/dashboards/iADxJYpDKPqpF2T2k72mQNFxZYLDGe8XJ6Ot8ylK?org_slug=default

Here is the 500 result I see when I request the shareable URL:

![screenshot 2017-08-03 13 20 32](https://user-images.githubusercontent.com/119884/28934329-8ffee2b6-784e-11e7-9b91-211915a35234.png)

**Comment by alison985** [comment] 2017-08-04 11:14
Thank you for the reproducible example @jaredkerim. This appears to happen because the last tile has a data source of "JSON URL Fetcher". When I try to reproduce with a new dashboard (i.e. https://sql.telemetry.mozilla.org/dashboard/alison-test-for-issue-166 ) the public url works fine until I add a widget with the "JSON URL Fetcher" data source.

@robotblake could you please let me know what is different between the permissions for the "JSON URL Fetcher" and the "Tiles" data sources in production?

**Comment by arikfr** [comment] 2017-08-07 17:39
Does any of the widgets on this dashboard use a parameter?

**Comment by alison985** [comment] 2017-08-08 15:33
@arikfr Yes and that was one of the first things I tested for. However, parameter or no parameter did not make a difference in reproduction of the issue.

**Comment by arikfr** [comment] 2017-08-08 16:15
See the discussion here: https://github.com/getredash/redash/issues/1909, I think it will help you understand the issue.

**Comment by arikfr** [comment] 2017-08-08 16:15
And also: https://github.com/getredash/redash/issues/1194.

**Comment by alison985** [comment] 2017-08-09 16:42
Thanks Arik.

Blake found this stacktrace: https://irccloud.mozilla.com/pastebin/v62qzsmf/ and noted "If a query gets added to a dashboard page without having been run in the background it never sets the "latest_query_data_id" field" so I currently think this is a separate issue.

**Comment by arikfr** [comment] 2017-08-09 17:04
This is exactly the issue described in getredash#1194.

**Comment by alison985** [comment] 2017-08-14 18:22
PR #200

**Comment by madalincm** [comment] 2017-08-21 15:50
Verified in FF55(Win7) in STMO-stage

I can still reproduce this issue.
The simplest steps to reproduce this issue are:
1. Create a new dashboard
2. Add a text widget.
-- the public link for this dashboard will generate a 500 error when accessed.

Example of a dashboard which has this problem: https://pipeline-sql.stage.mozaws.net/dashboard/001dashboard 

Reopening the issue.

**Comment by alison985** [comment] 2017-08-22 20:19
@madalincm This dashboard on staging: https://pipeline-sql.stage.mozaws.net/dashboard/alison-test-for-166-dashboard-public-500 works fine at this public URL: https://pipeline-sql.stage.mozaws.net/public/dashboards/Yt0nPgg1b0ioAySc5q0a9RV5jIZG56RHWBSzm5sp?org_slug=default I think you may have found a separate issue.

**Comment by madalincm** [comment] 2017-08-24 08:12
I have logged a new issue where we can track the problem with dashboards that contain a text widget where the original issue is still reproducing - #220 

I created other dashboards that contain visualization widgets and also tried with Alison dashboard and can't reproduce it. I will close this bug and continue the tracking of the issue with text widget dashboards in #220

**Closed by madalincm** 2017-08-24 08:12 UTC
Labels: in progress
