### ISSUE TITLE
Download dataset link broken until query is saved

### ISSUE THREAD

**Issue by georgf** [mozilla/redash#335] opened 2018-02-12 10:58 UTC
- Start new query
- enter "describe main_summary"
- execute
- try downloading results as csv or excel

Results:
- links point to "<blah>/undefined/<blah>"

Once i save the query it's working.

**Comment by emtwo** [comment] 2018-03-14 18:22
I am unable to reproduce this issue in my local dev build and on staging. I can successfully download query results for unsaved queries.

**Comment by emtwo** [comment] 2018-04-11 03:54
This should be resolved in prod now

**Closed by emtwo** 2018-04-11 03:54 UTC
Labels: ready

**Comment by madalincm** [comment] 2018-04-11 13:10
Issue is no longer reproducing. Verified as fixed in FF59(win7) in stmo-stage and stmo-prod
